### ISSUE TITLE
Issue while compilation of the new version 

### ISSUE THREAD

**Issue by pankajd-57** [mercanca/spart#19]
Thank you for patch. However, 

after downloading patched version I retried the compilation pf spart by issuing below command 
##############################
gcc -lslurm  spart.c -o spart -I/opt/slurm-21/include -L/opt/slurm-21/lib  
#################################

 In file included from spart.c:20:
spart_output.h: In function ‘sp_column_header_print’:
spart_output.h:229:47: warning: ‘%*s’ directive output may be truncated writing up to 2147483648 bytes into a region of size 64 [-Wformat-truncation=]
  229 |     snprintf(cresult, SPART_MAX_COLUMN_SIZE, "%*s", spcol->column_width,
      |                                               ^~~
spart_output.h:229:46: note: assuming directive output of 4095 bytes
  229 |     snprintf(cresult, SPART_MAX_COLUMN_SIZE, "%*s", spcol->column_width,
      |                                              ^~~~~
spart_output.h:229:5: note: ‘snprintf’ output between 1 and 2147483649 bytes into a destination of size 64
  229 |     snprintf(cresult, SPART_MAX_COLUMN_SIZE, "%*s", spcol->column_width,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  230 |              spcol->line1);
      |              ~~~~~~~~~~~~~
spart_output.h:232:47: warning: ‘%*s’ directive output may be truncated writing up to 2147483648 bytes into a region of size 64 [-Wformat-truncation=]
  232 |     snprintf(cresult, SPART_MAX_COLUMN_SIZE, "%*s", spcol->column_width,
      |                                               ^~~
spart_output.h:232:46: note: assuming directive output of 4095 bytes
  232 |     snprintf(cresult, SPART_MAX_COLUMN_SIZE, "%*s", spcol->column_width,
      |                                              ^~~~~
spart_output.h:232:5: note: ‘snprintf’ output between 1 and 2147483649 bytes into a destination of size 64
  232 |     snprintf(cresult, SPART_MAX_COLUMN_SIZE, "%*s", spcol->column_width,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  233 |              spcol->line2);
      |              ~~~~~~~~~~~~~
spart.c: In function ‘main’:
spart.c:731:56: warning: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size between 0 and 4095 [-Wformat-truncation=]
  731 |       snprintf(mem_result, SPART_INFO_STRING_SIZE, "%s(%s)",
      |                                                        ^~
  732 |                spgres[0].gres_name, strtmp);
      |                                     ~~~~~~
spart.c:731:7: note: ‘snprintf’ output between 3 and 8193 bytes into a destination of size 4096
  731 |       snprintf(mem_result, SPART_INFO_STRING_SIZE, "%s(%s)",
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  732 |                spgres[0].gres_name, strtmp);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spart.c:737:58: warning: ‘(’ directive output may be truncated writing 1 byte into a region of size between 0 and 4095 [-Wformat-truncation=]
  737 |         snprintf(mem_result, SPART_INFO_STRING_SIZE, ",%s(%s)",
      |                                                          ^
spart.c:737:9: note: ‘snprintf’ output between 4 and 8194 bytes into a destination of size 4096
  737 |         snprintf(mem_result, SPART_INFO_STRING_SIZE, ",%s(%s)",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  738 |                  spgres[j].gres_name, strtmp);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spart.c:750:56: warning: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size between 0 and 4095 [-Wformat-truncation=]
  750 |       snprintf(mem_result, SPART_INFO_STRING_SIZE, "%s(%s)",
      |                                                        ^~
  751 |                spfeatures[0].gres_name, strtmp);
      |                                         ~~~~~~
spart.c:750:7: note: ‘snprintf’ output between 3 and 8193 bytes into a destination of size 4096
  750 |       snprintf(mem_result, SPART_INFO_STRING_SIZE, "%s(%s)",
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  751 |                spfeatures[0].gres_name, strtmp);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spart.c:756:58: warning: ‘(’ directive output may be truncated writing 1 byte into a region of size between 0 and 4095 [-Wformat-truncation=]
  756 |         snprintf(mem_result, SPART_INFO_STRING_SIZE, ",%s(%s)",
      |                                                          ^
spart.c:756:9: note: ‘snprintf’ output between 4 and 8194 bytes into a destination of size 4096
  756 |         snprintf(mem_result, SPART_INFO_STRING_SIZE, ",%s(%s)",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  757 |                  spfeatures[j].gres_name, strtmp);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/ld: /tmp/ccVD4f7g.o: in function `main':
spart.c:(.text+0x3432): undefined reference to `slurm_init'
/usr/bin/ld: spart.c:(.text+0x34a9): undefined reference to `slurm_perror'
/usr/bin/ld: spart.c:(.text+0x34eb): undefined reference to `slurm_perror'
/usr/bin/ld: spart.c:(.text+0x3b1d): undefined reference to `slurm_load_ctl_conf'
/usr/bin/ld: spart.c:(.text+0x3b2d): undefined reference to `slurm_perror'
/usr/bin/ld: spart.c:(.text+0x3b50): undefined reference to `slurm_load_jobs'
/usr/bin/ld: spart.c:(.text+0x3b60): undefined reference to `slurm_perror'
/usr/bin/ld: spart.c:(.text+0x3b83): undefined reference to `slurm_load_node'
/usr/bin/ld: spart.c:(.text+0x3b93): undefined reference to `slurm_perror'
/usr/bin/ld: spart.c:(.text+0x3bb8): undefined reference to `slurm_load_partitions'
/usr/bin/ld: spart.c:(.text+0x3bc8): undefined reference to `slurm_perror'
/usr/bin/ld: spart.c:(.text+0x3cba): undefined reference to `slurmdb_connection_get'
/usr/bin/ld: spart.c:(.text+0x3cd8): undefined reference to `slurm_perror'
/usr/bin/ld: spart.c:(.text+0x3d05): undefined reference to `slurm_list_create'
/usr/bin/ld: spart.c:(.text+0x3d25): undefined reference to `slurm_list_append'
/usr/bin/ld: spart.c:(.text+0x3d2f): undefined reference to `slurm_list_create'
/usr/bin/ld: spart.c:(.text+0x3d4f): undefined reference to `slurmdb_associations_get'
/usr/bin/ld: spart.c:(.text+0x3d65): undefined reference to `slurm_list_iterator_create'
/usr/bin/ld: spart.c:(.text+0x3d7b): undefined reference to `slurm_list_count'
/usr/bin/ld: spart.c:(.text+0x3dc1): undefined reference to `slurm_list_next'
/usr/bin/ld: spart.c:(.text+0x3dec): undefined reference to `slurm_list_count'
/usr/bin/ld: spart.c:(.text+0x3e36): undefined reference to `slurmdb_qos_get'
/usr/bin/ld: spart.c:(.text+0x3e4c): undefined reference to `slurm_list_iterator_create'
/usr/bin/ld: spart.c:(.text+0x3e6c): undefined reference to `slurm_list_iterator_reset'
/usr/bin/ld: spart.c:(.text+0x3eb2): undefined reference to `slurm_list_next'
/usr/bin/ld: spart.c:(.text+0x3f17): undefined reference to `slurm_list_count'
/usr/bin/ld: spart.c:(.text+0x3f39): undefined reference to `slurm_list_iterator_create'
/usr/bin/ld: spart.c:(.text+0x3f86): undefined reference to `slurm_list_next'
/usr/bin/ld: spart.c:(.text+0x400b): undefined reference to `slurm_list_iterator_destroy'
/usr/bin/ld: spart.c:(.text+0x4023): undefined reference to `slurm_list_iterator_destroy'
/usr/bin/ld: spart.c:(.text+0x4032): undefined reference to `slurm_list_destroy'
/usr/bin/ld: spart.c:(.text+0x4041): undefined reference to `slurm_list_iterator_destroy'
/usr/bin/ld: spart.c:(.text+0x4050): undefined reference to `slurm_list_destroy'
/usr/bin/ld: spart.c:(.text+0x4b57): undefined reference to `slurm_get_select_nodeinfo'
/usr/bin/ld: spart.c:(.text+0x7ad2): undefined reference to `slurm_free_job_info_msg'
/usr/bin/ld: spart.c:(.text+0x7ae1): undefined reference to `slurm_free_node_info_msg'
/usr/bin/ld: spart.c:(.text+0x7af0): undefined reference to `slurm_free_partition_info_msg'
/usr/bin/ld: spart.c:(.text+0x7aff): undefined reference to `slurm_free_ctl_conf'
collect2: error: ld returned 1 exit status

Please help, as I want to use the utility. Thank you.

**Comment by mercanca** [comment]
unfortunately, I don't understand why it not compile, and I don't know any solution.  :-(

**Comment by ChristopherBottomsOMRF** [comment]
I'm getting an `unknown type name 'ListIterator'` error during compilation (gcc version 9.4.0):

    $ gcc -lslurm spart.c -o spart -I/path/to/slurm/include -L/path/to/slurm/lib 
    spart.c: In function 'main':
    spart.c:45:3: error: unknown type name 'ListIterator'
       45 |   ListIterator itr = NULL;

**Comment by chriswasser** [comment]
Just FYI, I have created a fork of the repository and fixed errors related to the changes in the SLURM API (see: [here](https://github.com/chriswasser/spart)). With these updates, `spart` works on our cluster using SLURM 25.05.5 - any later updates to SLURM might break other things, but for now it seems fine:

```sh
$ git clone https://github.com/chriswasser/spart.git
$ cd spart
$ CPATH="/opt/slurm/current/include:${CPATH}" LIBRARY_PATH="/opt/slurm/current/lib:${LIBRARY_PATH}" "${CC}" -o spart spart.c -lslurm
$ LD_LIBRARY_PATH="/opt/slurm/current/lib:${LD_LIBRARY_PATH}" ./spart
```

Of course you need to adjust the `CPATH`, `LIBRARY_PATH`, and `LD_ LIBRARY_PATH` to your SLURM deployment 🤓 Instead of including the `lib` path in `LD_ LIBRARY_PATH`, it would be possible to specify the path within the RPath as well.

Best of luck and greetings,

Christian
