### ISSUE TITLE
`unknown type name 'ListIterator'` error during compilation

### ISSUE THREAD

**Issue by ChristopherBottomsOMRF** [mercanca/spart#21]
I'm getting an `unknown type name 'ListIterator'` error during compilation (gcc version 9.4.0):

    $ gcc -lslurm spart.c -o spart -I/path/to/slurm/include -L/path/to/slurm/lib 
    spart.c: In function 'main':
    spart.c:45:3: error: unknown type name 'ListIterator'
       45 |   ListIterator itr = NULL;

**Comment by chriswasser** [comment]
Just FYI, I have created a fork of the repository and fixed errors related to the changes in the SLURM API (see: [here](https://github.com/chriswasser/spart)). With these updates, `spart` works on our cluster using SLURM 25.05.5 - any later updates to SLURM might break other things, but for now it seems fine:

```sh
$ git clone https://github.com/chriswasser/spart.git
$ cd spart
$ CPATH="/opt/slurm/current/include:${CPATH}" LIBRARY_PATH="/opt/slurm/current/lib:${LIBRARY_PATH}" "${CC}" -o spart spart.c -lslurm
$ LD_LIBRARY_PATH="/opt/slurm/current/lib:${LD_LIBRARY_PATH}" ./spart
```

Of course you need to adjust the `CPATH`, `LIBRARY_PATH`, and `LD_ LIBRARY_PATH` to your SLURM deployment 🤓 Instead of including the `lib` path in `LD_ LIBRARY_PATH`, it would be possible to specify the path within the RPath as well.

Best of luck and greetings,

Christian
